ARG from
FROM ${from} as base
LABEL org.opencontainers.image.authors="armando.ucf@gmail.com"

ARG duid=9000
ARG dgid=9000
ARG uname=ezdev
ARG gname=ezdev

RUN set -x \
	&& apk add --no-cache \
		bash shadow \
	&& addgroup -g ${dgid} ${gname} \
	&& adduser -u ${duid} -s /bin/bash -G ${gname} -D ${uname}

SHELL ["/bin/bash", "-c"]

COPY container-scripts/entrypoint-*.sh /opt/container-scripts/
#COPY container-scripts/entrypoint-ezdev.sh /opt/container-scripts/entrypoint-ezdev.sh
COPY container-scripts/entrypoint.d/root/10-modify-ezdev.sh /opt/container-scripts/entrypoint.d/root/
COPY container-scripts/entrypoint.d/ezdev/11-env.sh /opt/container-scripts/entrypoint.d/ezdev/

ENTRYPOINT ["/opt/container-scripts/entrypoint-root.sh"]
CMD ["/bin/bash"]

FROM base as gosu-build

ENV GOSU_VERSION 1.17

RUN set -eux; \
	\
	apk add --no-cache --virtual .gosu-deps \
	ca-certificates \
	dpkg \
	gnupg \
	; \
	\
	dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')" ; \
	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch" ; \
	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc" ; \
	\
	# verify the signature
	export GNUPGHOME="$(mktemp -d)" ; \
	gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 ; \
	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu ; \
	gpgconf --kill all ; \
	rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc ; \
	\
	# clean up fetch dependencies
	apk del --no-network .gosu-deps ; \
	\
	chmod +x /usr/local/bin/gosu ; \
	#&& chmod +s /usr/local/bin/gosu \
	# verify that the binary works
	gosu --version ; \
	gosu nobody true

FROM base as base-dev

RUN set -x \
	&& apk add --no-cache \
		sudo \
		git git-lfs openssh \
	&& echo "${uname} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${uname} 

COPY --from=gosu-build /usr/local/bin/gosu /usr/local/bin/gosu

USER ${uname}

RUN mkdir ~/.vscode-server

USER root

FROM base as base-prod

RUN set -x \
	&& apk add --no-cache \
		sudo \
	&& echo "${uname} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${uname} 

COPY --from=gosu-build /usr/local/bin/gosu /usr/local/bin/gosu

USER root
